env:
  TEST_PASSWORD:  "thisisatest"

steps:
  - label: "REDACT"
    command: echo "This is a $TEST_PASSWORD that is thisisatest"
  - command: MY_SECRET="12345ff6789" echo "Testing 12345ff6789 $MY_SECRET thisisatest"
