steps:
  # simple mode
  - name: ":mac: macOS"
    command: "echo darwin {{matrix}}"
    matrix:
      - "amd64"
      - "arm64"

  # explosion mode
  - name: ":mac: macOS"
    command: "echo darwin {{matrix.arch}}"
    matrix:
      setup:
        arch:
          - "amd64"
          - "arm64"

  # kitchen sink
  - name: "Build :hammer:"
    command: "echo {{matrix.os}} {{matrix.arch}}"
    env:
      GO_ARCH: "{{matrix.arch}}"
      GO_OS:" {{matrix.os}}"
    matrix:
      setup:
        arch:
          - "amd64"
          - "arm64"
        os:
          - "windows"
          - "linux"
      adjustments:
        - with:
            arch: "windows"
            os: "arm64"
          soft_fail: true