env:
  ANDROID_SDK_ROOT: "/home/samuel/Android/Sdk"

steps:
  - command: ./gradlew androidDependencies
    label: "Dependencies"

  - command: ./gradlew test
    label: "Test"

  - command: ./gradlew check
    label: "Lint"

  - command: ./gradlew assemble
    label: "Build"
    artifact_paths:
      - app/build/outputs/apk/release/app-release-unsigned.apk

