steps:
  - command: TEST_PASSWORD="testtest"
    label: "Another"
  - command: echo "This is a $TEST_PASSWORD"
    label: "Test the label?"
  - command: echo "This is a $TEST_PASSWORD WITHOUT A LABEL"
  - command: echo $TEST_PASSWORD
