steps:
  - command: echo "BUILD"
    key: build
  
  - command: echo "LINT"
    key: lint
    
  - block: "Thou shall not pass"
    depends_on: 
      - build 
      - lint

 - command: echo "For real now?"  
