env:
  TEST_PASSWORD:  "thisisatest"
  MY_SECRET: "12345ff6789"

steps:
  - label: "REDACT"
    command: echo "This is a $TEST_PASSWORD that is thisisatest"
  - command: echo "Testing 12345ff6789 $MY_SECRET thisisatest"
