steps:
  - command: echo "Command fails" && exit 1
    key: step-a
  - command: echo "step-b does not run" && exit 0
    key: step-b
    depends_on:
      - step: step-a
  - command: "step-c runs even when step-b does not"
    key: step-c
    depends_on:
      - step: step-b
        allow_failure: true
