steps:
  - block: "Who is this?"
    prompt: "What is your name?"
    fields: 
      - text: "Name"
        key: "name"
        hint: "Be as informal as you like."
      
  - command: echo "Hello $(buildkite-agent meta-data get release-name)"
    label: ":rocket:"