env:
  ANDROID_SDK_ROOT: "/home/samuel/Android/Sdk"

steps:
  - command: chmod +x ./gradlew
    label: "Why CHMOd why" 

  - command: ./gradlew androidDependencies
    label: "Dependencies"

  - command: ./gradlew test
    label: "Test"

  - command: ./gradlew check
    label: "Lint"

  - command: ./gradlew assemble
    label: "Build"

