steps:
  # simple mode
  - name: ":mac: macOS"
    command: "echo darwin {{matrix}}"
    matrix:
      - "amd64"   # simple array
      - "arm64"

  # explosion mode
  - name: "💥 :mac: macOS"
    command: "echo darwin {{matrix.arch}}"
    matrix:
      setup: # setup -> make the matrix from this
        arch:
          - "amd64" # more complex hash
          - "arm64"

  # kitchen sink
  - name: "Build :hammer:"
    command: "echo {{matrix.os}} {{matrix.arch}}"
    env:
      GO_ARCH: "{{matrix.arch}}" # User defined -> 
      GO_OS: "{{matrix.os}}"
    matrix:
      setup:
        arch:
          - "amd64"
          - "arm64"
        os:
          - "windows"
          - "linux"
      adjustments: # adjustments -> not these OR add theses?
        - with:
            arch: "macos"
            os: "arm64"
          soft_fail: true