env:
  TEST_PASSWORD:  "thisisatest"

steps:
  - label: "Redact"
    command: 
      - echo "This is a secret variable in a string: $TEST_PASSWORD"
      - echo "This is the same content in plain text in a string thisisatest"
