steps:
  - command: ./gradlew androidDependencies
    label: "Dependencies"

  - command: ./gradlew test
    label: "Test"

  - command: ./gradlew check
    label: "Lint"

  - command: ./gradlew assemble
    label: "Build"

