steps:
  - block: "Who is this?"
    prompt: "What is your name?"
    fields: 
      - text: "Name"
        key: "name"
        hint: "Be as informal as you like."
      
  - command: 
      - RELEASE_NAME=$(buildkite-agent meta-data get name || echo "Anon")
      - echo "Hello $RELEASE_NAME"
    label: ":rocket:"