env:
  TEST_PASSWORD:  "thisisatest"

steps:
  - label: "This should hide things? Or not?"
    command: echo "This is a $TEST_PASSWORD that is thisisatest"
  - command: export MY_SECRET="123456789" echo "Testing 123456789"
